spring.application.name=banking
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=Madhu@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
keycloak.server-url=http://localhost:8180
keycloak.realm=banking-realm
keycloak.admin-client-id=banking-admin
keycloak.admin-client-secret=hyXhSOjFFRJQTcALPUQdiN7OvGS0dMyfR0puiXqTsfETgZNYsbtIMpqXgG1v6HMyMYsOIpQbt1eyoyY1mvmZx4
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/banking-realm